# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/z1top_proj/z1top_proj.cache/wt [current_project]
set_property parent.project_path /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/z1top_proj/z1top_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/defines.vh
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/Opcode.vh
}
read_mem /home/cc/eecs151/sp20/class/eecs151-abm/riscv/software/bios151v3/bios151v3.mif
read_verilog -library xil_defaultlib {
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/wb.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/ex_wb.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/ex.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/id.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/id_ex.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/mux.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/Riscv151.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/alu.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/alu_control.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/branch_comp.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/io_circuits/button_parser.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/change_mem_wr.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/clk_wiz.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/control_unit.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/EECS151.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/io_circuits/debouncer.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/dmem_wr.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/io_circuits/edge_detector.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/forwarding_unit.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/riscv_core/imm_gen.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/io_circuits/synchronizer.v
  /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/src/z1top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/constrs/pynq-z1.xdc
set_property used_in_implementation false [get_files /home/cc/eecs151/sp20/class/eecs151-abm/riscv/hardware/constrs/pynq-z1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top z1top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef z1top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file z1top_utilization_synth.rpt -pb z1top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
