# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/z1top_proj/z1top_proj.cache/wt [current_project]
set_property parent.project_path C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/z1top_proj/z1top_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/z1top_proj/z1top_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/defines.vh
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/Opcode.vh
}
read_mem C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/software/bios151v3/bios151v3.mif
read_verilog -library xil_defaultlib {
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/EECS151.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/Riscv151.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/alu.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/alu_control.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/branch_comp.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/button_parser.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/change_mem_wr.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/clk_wiz.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/ID/control_unit.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/accelerator/conv2D_compute.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/accelerator/conv2D_mem_if.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/accelerator/conv2D_naive.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/accelerator/conv_controller.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/debouncer.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/dmem_wr.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/edge_detector.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/ex.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/ex_wb.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/fifo.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/EX/forwarding_unit.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/ID/id.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/ID/id_ex.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/ID/imm_gen.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/accelerator/io_dmem_controller.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/WB/load_type.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/mux.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/synchronizer.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/uart_receiver.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/io_circuits/uart_transmitter.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/riscv_core/WB/wb.v
  C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/src/z1top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/constrs/pynq-z1.xdc
set_property used_in_implementation false [get_files C:/Users/Jerry/Desktop/eecs151/workspace/project_skeleton_sp20/hardware/constrs/pynq-z1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top z1top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef z1top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file z1top_utilization_synth.rpt -pb z1top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
